import { Fragment, useState } from 'react';
import Head from 'next/head'

import SoundBoard from '../components/SoundBoard'

export default function Home() {
  const [sounds, setSounds] = useState(require('../sounds.json'));

  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
      </Head>

      <main className="container py-5">
        <div className="title pb-3">
          <h1>Calibrate Soundboard</h1>
        </div>
        <div className="soundboard">
          <SoundBoard sounds={sounds} />
        </div>
      </main>

      <footer className="text-center">
        <p>Built by Mathieu De Meue</p>
      </footer>
    </Fragment>
  )
}
